extends Node2D

const LEVEL_SIZE:	int = 1
var room_scene: 	PackedScene = preload("res://scenes/autogenerated_room.tscn")
var passage_scene: 	PackedScene = preload("res://scenes/autogenerated_passage.tscn")
var level:			Array
var active_scene:	int

func init_level():
	for i in LEVEL_SIZE:
		level.append(passage_scene.instantiate())
		level.back().set_player($player)
		
		level.append(room_scene.instantiate())
		level.back().set_player($player)

func handle_scene_progress():
	var scene_changed = false
	var old_scene = level[active_scene]
	var new_scene
	
	if level[active_scene].is_player_at_entrance():
		if active_scene > 0:
			scene_changed = true
			active_scene -= 1
			new_scene = level[active_scene]
	elif level[active_scene].is_player_at_exit():
		if active_scene < level.size() - 1:
			scene_changed = true
			active_scene += 1
			new_scene = level[active_scene]
	
	if scene_changed:
		remove_child(old_scene)
		add_child(new_scene)
		$player.position = new_scene.get_starting_position()
	
func _process(delta):
	for l in level: l.hide()
	
	level[active_scene].show()
	level[active_scene].tick()
	
	handle_scene_progress()

func _ready():
	active_scene = 0
	init_level()
	add_child(level[0])
	$player.position = level[0].get_starting_position()
