extends Node2D

enum STATE
{
	FREE_ROAM,
	IN_ROOM
}

const TILE_SIZE: 		int = 16
var half_tile_offset: 	Vector2
var enemy_rooms:		Array
var player_state:		STATE
var active_scene
var free_roam_level
var player_last_pos_before_transition: Vector2

func construct_enemy_room_nodes():
	for i in free_roam_level.NO_OF_ROOMS:
		var enemy_room = preload("res://scenes/autogenerated_room.tscn").instantiate()
		enemy_rooms.append(enemy_room)

func transition_to_enemy_room(room_id: int):
	player_last_pos_before_transition = $Player.position
	remove_child(active_scene)
	active_scene = enemy_rooms[room_id]
	add_child(active_scene)
	active_scene.reset()
	$Player.position = active_scene.get_starting_position()

func transition_to_free_roam_level():
	remove_child(active_scene)
	active_scene = free_roam_level
	add_child(active_scene)
	active_scene.reset()
	$Player.position = player_last_pos_before_transition

func handle_player_transfer():
	var active_entrance_tuple: Array = active_scene.get_activated_entrance()
	
	if active_entrance_tuple[0] && Input.is_action_pressed("E"):
		var type: String = active_entrance_tuple[1]
		if type == "enemy_room":
			var room_id = active_entrance_tuple[2]
			transition_to_enemy_room(room_id)
		elif type == "free_roam_level":
			transition_to_free_roam_level()
			
func init_player():
	player_state = STATE.FREE_ROAM
	$Player.position = free_roam_level.player_starting_point * TILE_SIZE + half_tile_offset
	free_roam_level.set_player_pointer($Player)
	
	for room in enemy_rooms:
		room.set_player_pointer($Player)
		
func init_free_roam_level():
	free_roam_level = preload("res://scenes/autogenerated_level.tscn").instantiate()
	active_scene = free_roam_level
	add_child(free_roam_level)
	
func handle_HUD():
	var health_blocks: int = ($Hud.HEALTH_BLOCKS * $Player.health) / $Player.MAX_HEALTH
	$Hud.set_visible_blocks(health_blocks)
	$Hud.set_position(active_scene.get_camera_position() - Vector2(245, 85))
	
func _process(delta):
	handle_player_transfer()
	handle_HUD()
	
func _ready():
	half_tile_offset = Vector2(TILE_SIZE / 2, TILE_SIZE / 2)
	
	init_free_roam_level()
	construct_enemy_room_nodes()
	init_player()
